<div class="jumbotron shade pt-5">
                    <h1>با عرض پوزش خطا در سیستم رخ داده است</h1>
                    <p class="c-grey font-weight-light font-italic">Indicate the current page’s location within a
                        navigational hierarchy that automatically adds separators via CSS.<br>

                        </p><h4 class="c-grey pt-3 pb-3">Breadcrumbs Shade</h4>
                        <h6 class="fnt-code text-dir-ltr mb-0 pb-0">breadcrumb-header shade </h6>
                        <hr class="mt-0 mb-4">
                        <!-- Breadcrumbs -->

                        <!-- breadcrumbs -->

                        <div class="row">
                            <div class="page-header breadcrumb-header shade p-3 mr-2 ml-2 m-2">
                                <div class="row align-items-end ">
                                    <div class="col-lg-8">
                                        <div class="page-header-title">
                                            <div class="d-inline">
                                                <h3 class="lite-text ">Breadcrumb Styles</h3>
                                                <span class="lite-text ">lorem ipsum dolor sit amet, consectetur
                                                    adipisicing elit</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <ol class="breadcrumb float-sm-right">
                                            <li class="breadcrumb-item "><a href="#"><i class="fas fa-home"></i></a>
                                            </li>
                                            <li class="breadcrumb-item "><a href="#">Home</a></li>
                                            <li class="breadcrumb-item active">Dashboard v1</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <h4 class="c-grey pt-3 pb-3">Breadcrumbs flat</h4>
                        <h6 class="fnt-code text-dir-ltr mb-0 pb-0">breadcrumb-header f-* </h6>
                        <hr class="mt-0 mb-4">
                        <div class="row">
                            <div class="page-header breadcrumb-header f-main  p-3 mr-2 ml-2 m-2">
                                <div class="row align-items-end ">
                                    <div class="col-lg-8">
                                        <div class="page-header-title">
                                            <div class="d-inline">
                                                <h3 class="lite-text ">Breadcrumb Styles</h3>
                                                <span class="lite-text ">lorem ipsum dolor sit amet, consectetur
                                                    adipisicing elit</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <ol class="breadcrumb c-all-white float-sm-right">
                                            <li class="breadcrumb-item "><a href="#"><i class="fas fa-home"></i></a>
                                            </li>
                                            <li class="breadcrumb-item "><a href="#">Home</a></li>
                                            <li class="breadcrumb-item active">Dashboard v1</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="page-header breadcrumb-header f-first  p-3 mr-2 ml-2 m-2">
                                <div class="row align-items-end ">
                                    <div class="col-lg-8">
                                        <div class="page-header-title">
                                            <div class="d-inline">
                                                <h3 class="lite-text ">Breadcrumb Styles</h3>
                                                <span class="lite-text ">lorem ipsum dolor sit amet, consectetur
                                                    adipisicing elit</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <ol class="breadcrumb c-all-dark float-sm-right">
                                            <li class="breadcrumb-item "><a href="#"><i class="fas fa-home"></i></a>
                                            </li>
                                            <li class="breadcrumb-item "><a href="#">Home</a></li>
                                            <li class="breadcrumb-item active">Dashboard v1</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h4 class="c-grey pt-3 pb-3">Breadcrumbs Outline</h4>
                        <h6 class="fnt-code text-dir-ltr mb-0 pb-0">breadcrumb-header outlined dashed </h6>
                        <hr class="mt-0 mb-4">
                        <div class="row">
                            <div class="page-header breadcrumb-header shade outlined dashed o-main c-main  p-3 mr-2 ml-2 m-2">
                                <div class="row align-items-end ">
                                    <div class="col-lg-8">
                                        <div class="page-header-title">
                                            <div class="d-inline">
                                                <h3 class="lite-text ">Breadcrumb Styles</h3>
                                                <span class="lite-text ">lorem ipsum dolor sit amet, consectetur
                                                    adipisicing elit</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <ol class="breadcrumb float-sm-right">
                                            <li class="breadcrumb-item "><a class="c-main" href="#"><i class="fas fa-home"></i></a></li>
                                            <li class="breadcrumb-item "><a class="c-main" href="#">Home</a></li>
                                            <li class="breadcrumb-item c-main active">Dashboard v1</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h6 class="fnt-code text-dir-ltr mb-0 pb-0">breadcrumb-header outlined o-* c-* </h6>
                        <hr class="mt-0 mb-4">
                        <div class="row">
                            <div class="page-header breadcrumb-header f-white outlined  o-main c-main  p-3 mr-2 ml-2 m-2">
                                <div class="row align-items-end ">
                                    <div class="col-lg-8">
                                        <div class="page-header-title">
                                            <div class="d-inline">
                                                <h3 class="lite-text ">Breadcrumb Styles</h3>
                                                <span class="lite-text ">lorem ipsum dolor sit amet, consectetur
                                                    adipisicing elit</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <ol class="breadcrumb float-sm-right">
                                            <li class="breadcrumb-item "><a class="c-main" href="#"><i class="fas fa-home"></i></a></li>
                                            <li class="breadcrumb-item "><a class="c-main" href="#">Home</a></li>
                                            <li class="breadcrumb-item c-main active">Dashboard v1</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="page-header breadcrumb-header shade outlined dashed o-main c-main  p-3 mr-2 ml-2 m-2">
                                <div class="row align-items-end ">
                                    <div class="col-lg-8">
                                        <div class="page-header-title">
                                            <div class="d-inline">
                                                <h3 class="lite-text ">Breadcrumb Styles</h3>
                                                <span class="lite-text ">lorem ipsum dolor sit amet, consectetur
                                                    adipisicing elit</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <ol class="breadcrumb float-sm-right">
                                            <li class="breadcrumb-item "><a class="c-main" href="#"><i class="fas fa-home"></i></a></li>
                                            <li class="breadcrumb-item "><a class="c-main" href="#">Home</a></li>
                                            <li class="breadcrumb-item c-main active">Dashboard v1</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h4 class="c-grey pt-3 pb-3">Breadcrumbs simple</h4>
                        <h6 class="fnt-code text-dir-ltr mb-0 pb-0">breadcrumb-header </h6>
                        <hr class="mt-0 mb-4">
                        <div class="row">
                            <div class="page-header breadcrumb-header  p-3 mr-2 ml-2 m-2">
                                <div class="row align-items-end ">
                                    <div class="col-lg-8">
                                        <div class="page-header-title">
                                            <div class="d-inline">
                                                <h3 class="lite-text ">Breadcrumb Styles</h3>
                                                <span class="lite-text ">lorem ipsum dolor sit amet, consectetur
                                                    adipisicing elit</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <ol class="breadcrumb float-sm-right">
                                            <li class="breadcrumb-item "><a href="#"><i class="fas fa-home"></i></a>
                                            </li>
                                            <li class="breadcrumb-item "><a href="#">Home</a></li>
                                            <li class="breadcrumb-item  active">Dashboard v1</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end of breadcrumbs -->


                </div>
